
#Spring
spring:
    redis:
       host: 120.77.182.151
       port: 6379
       password: dg5612651653
       timeout: 5000
       jedis:
         pool:
           #最大空闲数
           max-idle: 300
           #最大连接数
           max-total: 1000
           #最小空闲数
           min-idle: 1
           # 连接池最大阻塞等待时间（使用负值表示没有限制）
           max-wait: 5000ms
           #最大连接数
           max-active: 8
        #使用的数据库
       database: 16
#在控制台打印出运行的sql语句
logging:
  level:
     com.damai.dao : debug

